export const surpriseMePrompts = [
  'une chaise longue en forme d\'avocat',
  'une peinture à l\'huile surréaliste de Salvador Dalí représentant un chat jouant aux dames',
  'des ours en peluche faisant leurs courses au Japon, ukiyo-e',
  'une peinture à l\'huile de Matisse représentant un robot humanoïde jouant aux échecs',
  'un scientifique fou panda mélangeant des produits chimiques pétillants, art numérique',
  'une photographie macro de deux souris à Hawaï, portant chacune de petits maillots de bain et des planches de surf, art numérique',
  'une représentation 3D d\'un joli poisson tropical dans un aquarium sur un fond bleu foncé, art numérique',
  'un astronaute se prélassant dans une station balnéaire tropicale dans l\'espace, vaporwave',
  'un portrait à l\'huile d\'un capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre',
  'une vitre représentant un hamburger et des frites',
  'un dessin au crayon et à l\'aquarelle d\'une ville lumineuse du futur avec des voitures volantes',
  'un espace lounge éclairé par le soleil avec une piscine d\'eau claire et une autre de couleur rose pastel translucide, à côté d\'une grande fenêtre, art numérique',
  'un shiba inu lisant votre destin dans un hamburger géant, art numérique',
  '"une loutre de mer avec une boucle d\'oreille en perle" de Johannes Vermeer',
  'un dessin au pastel à l\'huile d\'un chat agacé dans un vaisseau spatial',
  'une peinture d\'un renard dans le style de La Nuit étoilée',
  'un bol de soupe ressemblant à un monstre, tricoté en laine',
  'un robot en peluche assis contre un mur jaune',
  'un coucher de soleil dans le style synthwave au-dessus de l\'eau réfléchissante de la mer, art numérique',
  'deux tours futuristes avec une passerelle couverte de feuillage luxuriant, art numérique',
  'une montgolfière arc-en-ciel volant au-dessus d\'un lac réfléchissant, rendu 3D',
  'une couverture de bande dessinée d\'un super- héros portant des écouteurs',
  'une explosion colorée centrée sur un fond noir',
  'une photo d\'un chien Samoyède avec la langue sortie en train de câliner un chat siamois blanc',
  'une photo d\'un monstre à fourrure blanche se tenant dans une pièce violette',
  'une photo de la sculpture de David de Michel-Ange',
   "un éléphant rose portant un chapeau de cowboy",
  "une pizza en forme de guitare électrique",
  "une ville flottante dans les nuages",
  "un cactus qui fait de la planche à voile",
  "une chaise de bureau faite de gelée",
  "un paysage de montagnes avec des arbres en forme de ballons",
  "un serpent qui tient un parapluie",
  "un château fait de bonbons et de gâteaux",
  "une voiture de course avec des ailes de papillon",
  "une méduse géante avec des couleurs fluorescentes",
  "une bibliothèque sous-marine",
  "une baleine qui saute dans un océan de glace",
  "un chat géant assis sur un immeuble de la ville",
  "un requin faisant du patin à glace",
  "un ordinateur portable fait de chocolat",
  "une forêt de champignons lumineux",
  "un crocodile en train de faire du yoga",
  "une guitare électrique faite de flammes",
  "une ville du futur avec des voitures volantes",
  "un tigre qui boit du thé dans une tasse géante",
  "un robot géant qui arrose des fleurs",
  "une pyramide de fruits tropicaux",
  "une licorne faisant du surf sur une vague géante",
  "un train de montagnes russes avec des rails en forme de dragons",
  "un arbre avec des branches en forme de mains",
  "une ville sous-marine avec des poissons volants",
  "un dinosaure qui conduit une voiture",
  "un château flottant dans les nuages",
  "un hippocampe géant transportant un bateau",
  "un arbre de Noël avec des guirlandes en forme de serpents",
  "une tasse de café avec une fumée en forme de dragon",
  "une ville du futur avec des ponts en forme de fleurs",
  "un chat géant avec des ailes de papillon",
  "un hibou en train de jouer au piano",
  "une bibliothèque en forme de montagne",
  "un monstre géant qui prend un bain",
  "un volcan en forme de chapeau de sorcière",
  "un loup en train de lire un livre dans une bibliothèque",
  "un château de sable géant avec des tours en forme de coquillages",
  "une ville flottante dans les nuages avec des ballons",
  "une pieuvre en train de danser avec des étoiles de mer",
  "une ville avec des maisons en forme de champignons",
  "un chat qui pêche dans une rivière de bonbons",
  "un ours en peluche qui conduit un train",
  "un champ de tournesols avec des nuages en forme de lapins",
  "un dragon faisant du skateboard",
  "un avion en papier géant",
  "un dauphin qui fait de la luge sur une colline enneigée",
  "une ville sous-marine avec des requins en forme de ballons",
  "un loup qui conduit une moto",
]
